---
#  Tasks to setup ssh authorized keys

- block:
    - name: Setup SSH authorized keys
      include_role:
        name: amtega.authorized_keys
      vars:
        authorized_keys_no_log: "{{ bootstrap_no_log }}"
  when: bootstrap_provisione_ssh_authorized_keys | bool
  tags:
    - role::bootstrap
    - role::bootstrap::authorized_keys
