---
#  Tasks to setup users

- block:
    - debug: msg="{{ bootstrap_ansible_user_final is bootstrap_password_match(bootstrap_ansible_password_final) }}"



    - fail:

    - name: setup ansible user
      user:
        name: "{{ bootstrap_ansible_user_final }}"
        shell: "{{ bootstrap_ansible_user_shell }}"
        group: "{{ bootstrap_ansible_user_group }}"
        password: "{{ bootstrap_ansible_password_final }}"
      register: bootstrap_create_ansible_user_result
      when: ansible_user != bootstrap_ansible_user_final

    - name: setup ansible become user
      user:
        name: "{{ bootstrap_ansible_become_user_final }}"
        shell: "{{ bootstrap_ansible_become_user_shell }}"
        group: "{{ bootstrap_ansible_become_user_group }}"
        password: "{{ bootstrap_ansible_become_password_final }}"
      register: bootstrap_create_ansible_become_user_result
      when:
        - bootstrap_ansible_become_final
        - ansible_become_user != bootstrap_ansible_become_user_final
  tags:
    - role::bootstrap
