---
#  Tasks to setup users

- block:
    - name: setup ansible user
      user:
        name: "{{ bootstrap_ansible_user_final }}"
        shell: "{{ bootstrap_ansible_user_shell }}"
        group: "{{ bootstrap_ansible_user_group }}"
        password: "{{ bootstrap_ansible_password_final }}"
      register: bootstrap_create_ansible_user_result
      when: >-
        bootstrap_ansible_user_final
        is not bootstrap_password_match(bootstrap_ansible_password_final)

    - name: setup ansible become user
      user:
        name: "{{ bootstrap_ansible_become_user_final }}"
        shell: "{{ bootstrap_ansible_become_user_shell }}"
        group: "{{ bootstrap_ansible_become_user_group }}"
        password: "{{ bootstrap_ansible_become_password_final }}"
      register: bootstrap_create_ansible_become_user_result
      when:
        - bootstrap_ansible_become_final
        - >-
          bootstrap_ansible_become_user_final
          is not bootstrap_password_match(
                   bootstrap_ansible_become_password_final)
  tags:
    - role::bootstrap
