---
# Role install tasks

- block:
    - include_tasks: proxy_client.yml
    - include_tasks: python.yml
    - include_tasks: epel.yml
    - include_tasks: packages.yml
  tags:
    - role::bootstrap
    - role::bootstrap::install
