---

- name: Setup python, epel and packages
  block:
    - ansible.builtin.include_tasks: proxy_client.yml
    - ansible.builtin.include_tasks: python.yml
    - ansible.builtin.include_tasks: epel.yml
    - ansible.builtin.include_tasks: packages.yml
  tags:
    - role::bootstrap
    - role::bootstrap::install
