---
#  Tasks to setup python

- block:
    - name: Install python
      script: files/install_python.sh
      register: bootstrap_install_python_result
      changed_when: bootstrap_install_python_result.rc == 1
      failed_when: bootstrap_install_python_result.rc == 2
      environment: "{{ proxy_client_environment }}"

    - name: Install minimum required packages
      package:
        name: "{{ item }}"
        use: >-
          {{ (bootstrap_distribution_version is version("8", "<"))
             | ternary("yum", "dnf") }}
        state: present
      loop: "{{ bootstrap_packages }}"
  tags:
    - role::bootstrap
    - role::bootstrap::install
