---
# Bootstrap the server to use ansible

- block:

  - name: setup auth information
    include: auth.yml

  - block:

    - name: setup pyhon
      include: python.yml

    - name: setup ansible users
      include: users.yml

    - name: reload facts
      setup:

    vars:
      ansible_user: "{{ bootstrap_ansible_user }}"
      ansible_password: "{{ bootstrap_ansible_password }}"
      ansible_become: "{{ bootstrap_become | default(false) }}"
      ansible_become_method: "{{ bootstrap_become_method | default('su') }}"
      ansible_become_user: "{{  bootstrap_become_user | default('root') }}"
      ansible_become_pass: "{{ bootstrap_become_pass | default('') }}"

  tags:
    - role::bootstrap
