---
# Bootstrap the server to use ansible

- block:
    - name: setup ansible connection facts
      include_tasks: facts.yml
      tags:
        - role::bootstrap

    - name: setup python
      include_tasks: install.yml
      tags:
        - role::bootstrap
        - role::bootstrap::install

    - name: setup ansible users
      include_tasks: configure.yml
      tags:
        - role::bootstrap
        - role::bootstrap::configure

    - name: reload facts
      setup:
  when: bootstrap_enable
