---
# Bootstrap the server to use ansible

- block:
    - name: Setup ansible connection facts
      include_tasks: facts.yml

    - block:
        - name: Setup python
          include_tasks: install.yml

        - block:
            - name: Setup ansible users
              include_tasks: users.yml

            - name: Setup SSH authorized keys
              include_tasks: authorized_keys.yml

            - name: Setup python virtualenv
              include_tasks: virtualenv.yml

            - name: Reload facts
              setup:
              when: >-
                bootstrap_install_python_result is changed
                or bootstrap_setup_venv_result is changed

      vars:
        ansible_user: "{{ bootstrap_ansible_user }}"
        ansible_password: "{{ bootstrap_ansible_password }}"
        ansible_become: "{{ bootstrap_become | default(false) }}"
        ansible_become_method: "{{ bootstrap_become_method | default('su') }}"
        ansible_become_user: "{{  bootstrap_become_user | default('root') }}"
        ansible_become_pass: "{{ bootstrap_become_pass | default('') }}"
        ansible_ssh_common_args: "{{ bootstrap_ansible_ssh_common_args }}"
        ansible_python_interpreter: >-
          {{ bootstrap_ansible_python_interpreter
             | default(
                 (bootstrap_distribution_version is version("8", "<"))
                 | ternary("/usr/bin/python",
                           "/usr/bin/python3")) }}
  when: bootstrap_enable | bool
  tags:
    - role::bootstrap
