---
#  Tasks to setup packages

- name: Setup packages
  include_role:
    name: amtega.packages
  vars:    
    packages_load_from_hostvars: no
    packages_os:
      fedora:
        all:
          - name: libselinux-python3
            state: present

          - name: python3-virtualenv
            state: present
      all:
        6:
          - name: python-virtualenv
            state: present

          - name: libselinux-python
            state: present
        7:
          - name: python-virtualenv
            state: present

          - name: libselinux-python
            state: present
        8:
          - name: python3-virtualenv
            state: present

          - name: python3-libselinux
            state: present

    packages_python: {}
