---
#  Tasks to setup users

- block:
    - name: Setup ansible user home directory
      user:
        name: "{{ bootstrap_ansible_user_to_update }}"
        create_home: yes
      register: bootstrap_ansible_user_home_result
      when: bootstrap_create_ansible_user_home | bool

    - name: Setup ansible user home directory parent dir
      file:
        path: "{{ bootstrap_ansible_user_home_result.home | dirname }}"
        owner: "{{ bootstrap_home_parent_dir_owner }}"
        group: "{{ bootstrap_home_parent_dir_group }}"
        mode: "{{ bootstrap_home_parent_dir_mode }}"
      when: bootstrap_ansible_user_home_result is changed

    - name: Setup ansible user
      user:
        name: "{{ bootstrap_ansible_user_to_update }}"
        shell: "{{ bootstrap_ansible_user_shell }}"
        group: "{{ bootstrap_ansible_user_group }}"
        groups: "{{ bootstrap_ansible_user_groups }}"
        password: >-
          {{ (bootstrap_ansible_user_needs_update | default(false))
             | ternary(bootstrap_ansible_new_password, omit) }}
      register: bootstrap_create_ansible_user_result
      when: bootstrap_provisone_ansible_user | bool

    - name: Setup ansible become user
      user:
        name: "{{ bootstrap_ansible_become_user_to_update }}"
        shell: "{{ bootstrap_ansible_become_user_shell }}"
        group: "{{ bootstrap_ansible_become_user_group }}"
        groups: "{{ bootstrap_ansible_become_user_groups }}"
        password: >-
          {{ (bootstrap_ansible_become_user_needs_update | default(false))
             | ternary(bootstrap_ansible_become_new_password, omit) }}
      register: bootstrap_create_ansible_become_user_result
      when:
        - bootstrap_provisone_ansible_become_user | bool
        - bootstrap_ansible_become_activated | bool
  tags:
    - role::bootstrap
    - role::bootstrap::configure
