---
#  Tasks to setup users

- block:
    - name: Setup ansible user
      user:
        name: "{{ bootstrap_ansible_user_to_update }}"
        shell: "{{ bootstrap_ansible_user_shell }}"
        group: "{{ bootstrap_ansible_user_group }}"
        password: "{{ bootstrap_ansible_new_password }}"
      register: bootstrap_create_ansible_user_result
      when:
        - bootstrap_provisone_ansible_user
        - bootstrap_ansible_user_needs_update

    - name: Setup ansible become user
      user:
        name: "{{ bootstrap_ansible_become_user_to_update }}"
        shell: "{{ bootstrap_ansible_become_user_shell }}"
        group: "{{ bootstrap_ansible_become_user_group }}"
        password: "{{ bootstrap_ansible_become_new_password }}"
      register: bootstrap_create_ansible_become_user_result
      when:
        - bootstrap_provisone_ansible_become_user
        - bootstrap_ansible_become_activated
        - bootstrap_ansible_become_user_needs_update
  tags:
    - role::bootstrap
    - role::bootstrap::configure
