---

- name: Setup users
  block:
    - name: Setup ansible user home directory
      ansible.builtin.user:
        name: "{{ bootstrap_ansible_user_to_update }}"
        create_home: yes
      register: bootstrap_ansible_user_home_result
      when:
        - bootstrap_provisone_ansible_user
        - bootstrap_create_ansible_user_home | bool

    - name: Setup ansible user home directory parent dir
      ansible.builtin.file:
        path: "{{ bootstrap_ansible_user_home_result.home | dirname }}"
        owner: "{{ bootstrap_home_parent_dir_owner }}"
        group: "{{ bootstrap_home_parent_dir_group }}"
        mode: "{{ bootstrap_home_parent_dir_mode }}"
      when: bootstrap_ansible_user_home_result is changed

    - name: Setup ansible user
      ansible.builtin.user:
        name: "{{ bootstrap_ansible_user_to_update }}"
        shell: "{{ bootstrap_ansible_user_shell }}"
        group: "{{ bootstrap_ansible_user_group }}"
        groups: "{{ bootstrap_ansible_user_groups }}"
        password: >-
          {{ (bootstrap_ansible_user_needs_update | default(false))
             | ternary(bootstrap_ansible_new_password, omit) }}
      register: bootstrap_create_ansible_user_result
      when: bootstrap_provisone_ansible_user | bool
      no_log: yes

    - name: Setup ansible become user
      ansible.builtin.user:
        name: "{{ bootstrap_ansible_become_user_to_update }}"
        shell: "{{ bootstrap_ansible_become_user_shell }}"
        group: "{{ bootstrap_ansible_become_user_group }}"
        groups: "{{ bootstrap_ansible_become_user_groups }}"
        password: >-
          {{ (bootstrap_ansible_become_user_needs_update | default(false))
             | ternary(bootstrap_ansible_become_new_password, omit) }}
      register: bootstrap_create_ansible_become_user_result
      when:
        - bootstrap_provisone_ansible_become_user | bool
        - bootstrap_ansible_become_activated | bool
      no_log: yes

    - name: Setup groups
      ansible.builtin.include_role:
        name: amtega.groups
      when: bootstrap_groups | length > 0
      vars:
        groups_load_from_hostvars: no
        groups_list: "{{ bootstrap_groups }}"
        groups_no_log: "{{ bootstrap_no_log | bool }}"

    - name: Setup users
      ansible.builtin.include_role:
        name: amtega.users
      when: bootstrap_users | length > 0
      vars:
        users_load_from_hostvars: no
        users: "{{ bootstrap_users }}"
        users_no_log: "{{ bootstrap_no_log | bool }}"
  tags:
    - role::bootstrap
    - role::bootstrap::configure