---
#  Tasks to setup python vittualenv

- block:
    - name: Setup python virtualenv
      command: >-
        {{ virtualenv_command }} \
        --python={{ ansible_python_interpreter }} \
        {{ (bootstrap_python_virtualenv_site_packages)
           | ternary("--system-site-packages", "") }} \
        {{ virtualenv }}
      args:
        creates: "{{ virtualenv }}"
      register: bootstrap_setup_venv_result
      vars:
        virtualenv: "{{ bootstrap_python_virtualenv }}"
        virtualenv_command: >-
          {{ bootstrap_python_virtualenv_command
             | default(
                 (bootstrap_distribution_version is version("8", "<"))
                 | ternary("/usr/bin/virtualenv",
                           "/usr/bin/virtualenv-3")) }}
        virtualenv_site_packages: >-
          {{ bootstrap_python_virtualenv_site_packages
             | default(none) }}
  when:
    - bootstrap_python_virtualenv is defined
    - bootstrap_python_virtualenv | length > 0
  tags:
    - role::bootstrap
    - role::bootstrap::virtualenv
