---

- name: Setup python virtualenv # noqa jinja[spacing]
  ansible.builtin.command: >-
    {{ virtualenv_command }} \
    --python={{ packages_python_virtualenv_python
                | default(ansible_python_interpreter) }} \
    {{ (bootstrap_python_virtualenv_site_packages)
       | ternary("--system-site-packages", "") }} \
    {{ virtualenv }}
  args:
    creates: "{{ virtualenv }}"
  register: bootstrap_setup_venv_result
  vars:
    distribution_major_version: >-
      {{ bootstrap_distribution_version.split(".") | first }}
    virtualenv: "{{ bootstrap_python_virtualenv }}"
    virtualenv_default_command: >-
      {{ (distribution_major_version == "7")
         | ternary("/usr/bin/virtualenv-3",
                   "/usr/bin/virtualenv") }}
    virtualenv_command: >-
      {{ bootstrap_python_virtualenv_command
         | default(virtualenv_default_command) }}
    virtualenv_site_packages: >-
      {{ bootstrap_python_virtualenv_site_packages
         | default(none) }}
  when:
    - bootstrap_python_virtualenv is defined
    - bootstrap_python_virtualenv | length > 0
  tags:
    - role::bootstrap
    - role::bootstrap::virtualenv
