---

- name: Converge
  hosts: molecule_hosts
  roles:
    - amtega.bootstrap
  tasks:
    - name: Test bootstrap_shadow_facts module with a list of users
      bootstrap_shadow_facts:
        usernames:
          - root
          - daemon
          - vagrant
      register: module_result
      failed_when: >-
        "root" not in module_result.shadows.keys() | list
        or "daemon" not in module_result.shadows.keys() | list
        or "vagrant" not in module_result.shadows.keys() | list

    - name: Test bootstrap_shadow_match filter
      assert:
        that: password is bootstrap_shadow_match(module_result.shadows.vagrant)
      vars:
        password: vagrant
