---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    box: centos/stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora34-${INSTANCE_UUID:-1}"
    box: fedora/34-cloud-base
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
  - name: "fedora35-${INSTANCE_UUID:-1}"
    box: fedora/35-cloud-base
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
provisioner:
  name: ansible
  inventory:
    hosts:
      molecule_hosts:
        vars:
          ansible_user: vagrant
          ansible_password: vagrant
          ansible_become: yes
          ansible_become_user: root
          ansible_become_pass: vagrant
          ansible_become_method: su
          bootstrap_enable: yes
          bootstrap_ansible_user: vagrant
          bootstrap_ansible_password: vagrant
          bootstrap_become: yes
          bootstrap_become_user: root
          bootstrap_become_pass: vagrant
          bootstrap_seconds_to_run: 300
          bootstrap_no_log: no
          key: >-
            {{ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCm9jwJbWL+UVufW9g7BgaaFE/"
               + "oNFNE70zmkIbuINauyxWwjzKcipjn6jmr4DU3XJMNusd1xJFB8BAE40C5m+eq"
               + "OdcWxDVtYupOJr7+YSTnsQU8Gk2PzhC4uhzD+P0Tso7Gscr0+24IYhpRlrh5S"
               + "oG71Z2drwTmMYgn8cfm+NdbbcpDRkJhL8DmSiDpdBW7amWZNSqsLOBO+et3MC"
               + "N1N99k9Djts8HqZdWl4fK3j8oOT3OR301QeH6HStQWbMr7QjP14Um8QzKvxNi"
               + "G4NK+1T9yzWmY0LkccJaH+5DIvbOwT3RsGreessowCSLvBNguSe9/jP4XJ6az"
               + "x/xwvgIQMk3NjDj7HkrOyygcSeHWzv6KY/K1X8+LR/sKRIlCnOXVTL/UNBQ04"
               + "qcsQ5IaObLX9BVAy6cdPNgdjMje0qH3f15u0m9AD/fqKMVHXVUqsyfEqgcZxN"
               + "FVZP1COTiflh+PaIiIAbaoQf7a8/quiug/Nmb/UMEpkyT2NwYKBRl6Y90W3ck"
               + "= user@acme.com" }}
          authorized_keys:
            - comment: Test key pair
              key: "{{ key }}"
              user: root
              state: present
      molecule_hosts_centos:
        vars:
          ansible_become_method: su
          bootstrap_become_method: su
          ansible_python_interpreter: /usr/bin/python
      molecule_hosts_centos_8:
        vars:
          ansible_python_interpreter: /usr/bin/python3
      molecule_hosts_fedora:
        vars:
          ansible_become_method: sudo
          ansible_python_interpreter: /usr/bin/python3
          bootstrap_become_method: sudo
verifier:
  name: ansible
