---

- name: Converge
  hosts: molecule_hosts
  roles:
    - role: amtega.bootstrap
      bootstrap_enable: true
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_become: yes
    ansible_become_user: root
    ansible_become_pass: vagrant
    ansible_become_method: >-
      {{ (inventory_hostname is search("centos"))
         | ternary("su", "sudo") }}
  tasks:
    - name: Test bootstrap_shadow_facts module with a list of users
      bootstrap_shadow_facts:
        usernames:
          - root
          - daemon
          - vagrant
      register: module_result
      failed_when: >-
        "root" not in module_result.shadows.keys() | list
        or "daemon" not in module_result.shadows.keys() | list
        or "vagrant" not in module_result.shadows.keys() | list

    - name: Test bootstrap_shadow_match filter
      assert:
        that: password is bootstrap_shadow_match(module_result.shadows.vagrant)
      vars:
        password: vagrant

    - name: Get ansible user
      getent:
        database: passwd
        key: "{{ ansible_user }}"
      register: get_ansible_user_result

    - name: Get ansible become user
      getent:
        database: passwd
        key: "{{ ansible_become_user }}"
      register: get_ansible_become_user_result

    - name: Verify ansible users
      assert:
        that:
          - >-
            ansible_user
              in get_ansible_user_result.ansible_facts.getent_passwd
          - >-
            ansible_become_user
              in get_ansible_become_user_result.ansible_facts.getent_passwd
