---

- name: Prepare
  hosts: molecule_hosts
  become: yes
  gather_facts: no
  tasks:
    - name: Setup python
      raw: "yum install -y {{ ansible_python_interpreter | basename }}"
      when: yes
      args:
        warn: no

    - name: Allow interactive password ssh authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        line: PasswordAuthentication yes

    - name: Restart sshd service
      service:
        name: sshd
        state: restarted
