---

- name: Prepare
  hosts: molecule_hosts
  become: yes
  gather_facts: no
  tasks:
    - name: Allow interactive password ssh authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        line: PasswordAuthentication yes

    - name: Restart sshd service
      service:
        name: sshd
        state: restarted
