---
#  Tasks to setup users in all operating systems

- block:

  - name: setup ansible user
    user:
      name: "{{ ansible_user_final }}"
      shell: "/bin/bash"
      group: "users"
      password: "{{ ansible_password_final }}"
    register: bootstrap_create_ansible_user_result

  - name: setup ansible become user
    user:
      name: "{{ ansible_become_user_final }}"
      shell: "/bin/bash"
      password: "{{ ansible_become_password_final }}"
    register: bootstrap_create_ansible_become_user_result
    when: ansible_become_final

  tags:
    - role::bootstrap
